import json
import os.path
from typing import List

import numpy as np
from tqdm import tqdm

from sentence_transformers import SentenceTransformer, util

# Load a pre-trained BERT-based model for sentence embeddings
model = SentenceTransformer('paraphrase-distilroberta-base-v1')

# Given texts
latin_data = [
    ["a posteriori", "im Nachhinein"],
    ["a priori", "von vornherein"],
    ["a verbis legis non est recedendum", "von den Worten des Gesetzes ist nicht abzugehen"],
    ["ab initio", "von Anfang an"],
    ["ab initio nullum semper nullum", "anfangs nichtig, immer nichtig"],
    ["ab intestato", "vom Testtamentslosen"],
    ["ab urbe condita", "ab Günderung der Stadt"],
    ["aberratio ictus", "Abirren des Schlages"],
    ["abolitio", "Aufhebung"],
    ["abrogatio", "Abschaffung"],
    ["absolutio", "Freisprechung"],
    ["absolutus sententia iudicis praesumitur innocens",
     "wer durch Gerichtsurteil freigesprochen worden ist, gilt als unschuldig"],
    ["abusus non tollit usum", "Missbrauch hebt ein Gebrauchsrecht nicht auf"],
    ["abusus", "Missbrauch"],
    ["acceptilatio", "förmliche Bestätigung der Erfüllung einer Stipulationsschuld"],
    ["accessio cedit principali", "die Nebensache teilt notwendig das Schicksal der Hauptsache"],
    ["accessio", "Zuwachs, das Hinzukommen, Hinzufügen"],
    ["accidentalia negotii", "Nebenbestimmungen eines Vertrags"],
    ["accusatio suspecti tutoris", "Anklage gegen einen verdächtigen Vormund, dem ein Treueverstoß vorgeworfen wird"],
    ["accusatio", "Anklage"],
    ["acquisitio hereditatis", "Erbschaftserwerb"],
    ["acquisitio", "Erwerb"],
    ["acta publica probant se ipsa", "öffentliche Akte beweisen sich selbst"],
    ["actio ad exhibendum", "Klage auf Vorweisung"],
    ["actio annalis", "einjährig befristetes Klagerecht"],
    ["actio auctoritatis", "Gewährschaftsklage"],
    ["actio certae creditae pecuniae", "Klage des bestimmten anvertraueten Geldes"],
    ["actio conducti", "Klage des Mieters"],
    ["actio confessoria", "Klage des Servitutsberechtigten"],
    ["actio contrario", "Wiederklage,Gegenklage des Nebenansrpuchsberechtigten"],
    ["actio de dolo/ actio doli", "Schadenersatzklage"],
    ["actio directa", "Hauptklage, direkte Klage des Haupanspruchsberechtigten"],
    ["actio empti", "Klage (des Käufers) aus dem Kaufvertrag"],
    ["actio ex stipulatu", "Klage aufgrund eines Schuldversprechens"],
    ["actio ex testamento", "Klage, die sich auf ein Testament gründet"],
    ["actio furti", "Diebstahlsklage"],
    ["actio in personam", "Klage gegen eine bestimmte Person"],
    ["actio in rem", "Klage auf eine Sache"],
    ["actio iniuriarum", "Klage wegen Persönlichkeitsverletzung"],
    ["actio locati", "Klage des Vermieters"],
    ["actio mandati", "Klage des Auftraggebers aus dem Auftragsvertrag"],
    ["actio mandati contrario", "(Gegen-)klage des Beauftragten aus dem Auftragsvertrag"],
    ["actio negatoria", "Eigentumsfreiheitsklage"],
    ["actio negotorium gestorum", "Klage aus der Geschäftsführung ohne Auftrag"],
    ["actio perpetua", "unbefristetes Klagerecht"],
    ["actio poenalis", "Strafklage (Klage auf Buße)"],
    ["actio publiciana", "publizianische Klage"],
    ["actuo quanti minoris", "Minderungslklage"],
    ["actio redhibitoria", "Wandlungsklage"],
    ["actio semel extincta non reviviscit", "eine einmal erloschener Anspruch lebt nicht wieder auf"],
    ["actio utilis", "verwendbar, brauchbar gemachte Klage"],
    ["actio venditi", "Klage des Verkäufers"],
    ["actio", "Handlung(en)/ Klage(n)"],
    ["actiones noxales", "Noxalklage"],
    ["actor sequitur forum rei", "der Kläger folgt dem Gerichtsstand des Beklagten"],
    ["actor", "Kläger/ Ankläger/ Verwalter/ Geschäftsführer"],
    ["actori incumbit onus probandi", "dem Kläger obliegt die Beweislast"],
    ["actus", "Recht, sein Vieh über fremden Grund zu treiben - Feldservitut"],
    ["ad absurdum", "gründlich widerlegen"],
    ["ad acta", "zu den Akten"],
    ["ad hoc", "zu diesem - diesen Fall betreffend"],
    ["ad infinitum", "bis ins Unendliche"],
    ["ad libitum", "nach Belieben, beliebig"],
    ["ad usum", "zum Gebrauch"],
    ["addictio", "prätorische Zusage, Zusprechen durch den Prätor"],
    ["aditio hereditatis", "Erbschaftsantritt/ Erbschaftsannahme"],
    ["aditio", "Antritt"],
    ["adiudicatio", "richterlicher Zuspruch durch Urteil"],
    ["adoptio imitatur naturam", "die Adoption ahmt die Natur nach"],
    ["adulterium", "Ehebruch"],
    ["advocatus", "Rechtsbeistand, Rechtsanwalt, Anwalt"],
    ["aedes", "Gebäude"],
    ["aequitas", "Billigkeit"],
    ["aequum est enim ut cuis participativ lucrum participet et damnum",
     "es ist gerecht, dass derjenige, der den Nutzen (aus etwas) zieht, auch an dem (daraus resultierenden) Schaden beteiligt sein soll"],
    ["aerarium", "die Staatskasse, das Staatsvermögen"],
    ["aes alienum", "'fremdes Geld' = Schulden"],
    ["aestimatio", "Schätzung"],
    ["aetas", "Lebensalter, Zeitalter"],
    ["affectus", "Zustand, Leidenschaft, Begierde"],
    ["agere in fraudem legis", "unter Umgehung des Gesetzes handeln"],
    ["agnatus proximus", "der nächste Blutsverwandte"],
    ["alieno facto ius alterius non mutatur", "durch eine fremde Tat wird das Recht eines anderen nicht verändert"],
    ["alieno nomine", "in fremdem Namen"],
    ["alius", "etwas anderes"],
    ["alius m., alia f., aliud n.", "ein anderer, eine andere, etwas anderes"],
    ["alluvio", "Anschwemmung von Erde, Landanschwemmung durch Flüsse"],
    ["alma mater", "nährende Mutter"],
    ["altera pars", "die Gegenpartei - der 'andere Teil'"],
    ["alteri stipulari nemo potest", "niemand kann sich für einen anderen etwas versprechen lassen"],
    ["ambiguitas contra stipulatorem", "Zweideutigkeit (wirkt) gegen den Stipulator"],
    ["ambiguitas", "Zwei-, Mehrdeutigkeit"],
    ["animus domini", "der Wille, eine Sache als die seine, (als Eigentümer) für sich zu behalten"],
    ["animus donandi", "Schenkungswille, -absicht"],
    ["animus negotii alieni gerendi", "Absicht, für einen anderen ein Geschäft zu führen"],
    ["animus novandi", "Erneurungsabsicht, -wille"],
    ["animus obligandi", "Verpflichtungswille"],
    ["animus possidendi", "Besitzwille"],
    ["animus rem alteri habendi", "der Wille, eine Sache für einen anderen innezuhaben"],
    ["animus rem sibi hanbendi", "Besitzwille"],
    ["animus", "Absicht, Wille (der Handelnden)"],
    ["annus", "Jahr"],
    ["appellatio", "Berufung"],
    ["approbatio", "Bestätigung, Billigung"],
    ["aquae ductur", "das Recht, eine Wasserleitung über ein fremdes Grundstück zu führen (Feldservitut)"],
    ["arbitrium iudicis", "richterliches Ermessen"],
    ["arbitrium", "Schiedsspruch"],
    ["argumenta non sunt numeranda sed ponderanda", "die Gründe sind nicht abzuzählen, sondern zu Gewichten"],
    ["argumentum a maiori ad minus", "Schlussfolderung vom Größeren auf das Kleine"],
    ["argumentum a minori ad maius", "Schlussfolderung vom Kleineren auf das Größere"],
    ["argumentum e contrario", "Umkehrschluss"],
    ["argumentum", "Beweismittel, Beweisgrund, Merkmal"],
    ["assignatio", "Anweisung"],
    ["auctor", "Gewährsmann, Gewährleister, Urheber, Rechtsvorgänger"],
    ["auctoritas", "Macht, Ansehen, Autorität, Gewähr, Bürgschaft, Gültigkeit"],
    ["audiatur et altera pars", "es möge auch der andere Teil gehört werden"],
    ["beati possidentes", "Glücklich die Besitzenden"],
    ["bella gerant alii, tu, felix, Austria, nube!",
     "Andere mögen Krieg führend, du, glückliches Österreich, heirate!"],
    ["bellum defensivum", "Verteidigungskrieg"],
    ["bellum gerere", "Krieg führen"],
    ["bellum", "Krieg"],
    ["beneficium", "(Rechts-)Wohltat, Vergünstigung"],
    ["bilateralis/ unilateralis", "zweiseitig/ einseitig"],
    ["bono fide", "gutgläubig, redlich"],
    ["bona fides", "die 'gute Treue' - der gute Glaube"],
    ["bona fides praesumitur", "der gute Glaube wird vermutet"],
    ["bonae fidei possessor", "Besitzer guten Glaubens"],
    ["boni mores", "die guten Sitten"],
    ["bonorum possessio", "Erbschaftsbesitz"],
    ["bonorum possessor", "Erbschaftsbesitzer"],
    ["bonum commune", "Gemeinwohl"],
    ["bonum publicum", "Staatswohl"],
    ["bonum", "das Gute"],
    ["capacitas", "Fähigkeit"],
    ["capitis deminutio", "Änderung bzw Schmälerung der Rechtsfähigkeit"],
    ["capitis deminutio maxima", "Verlust der Freihait"],
    ["caput", "Haupt, Kopf"],
    ["casum sentit dominus", "den Zufall spürt der Herr (Eigentümer)"],
    ["casus", "Fall, Zufall"],
    ["causa cognita", "nahc Untersuchung des Falles"],
    ["causa", "Ursache, (Rechts)grund, Titel"],
    ["cautela abundans non nocet", "übertriebene Vorsicht schadet nicht"],
    ["cautio", "(Versprechen zur) Sicherheitsleistung, Kaution"],
    ["caveat emptor", "der Käufer sei auf der Hut"],
    ["certa pecunia", "eine bestimmte Geldsumme, ein bestimmtes Vermögen"],
    ["certum dare", "eine bestimmte Sache leisten"],
    ["certum", "das (genau) Bestimmte, das Sichere"],
    ["cessante occasione legis non cessat lex ipsa",
     "bei Wegfall des äußeren Anlasses für ein Gesetz hört das Gesetz nicht zu wirken auf"],
    ["cessante ratione cessat lex ipsa", "fällt der Zweck eines Gesetzes weg, fällt das Gesetz selbst weg"],
    ["cessante ratione legis cessat lex ipsa",
     "bei Wegfall des Zweckes bzw inneren Grundes eines Gesetzes hört auch die Wirksamkeit des Gesetzes auf"],
    ["cessio legis",
     "gesetzliche Forderungsübergang, Übergang einer Forderung auf eine andere Person aufgrund des Gesetzes"],
    ["cessio voluntario", "freiwillige Abtretung"],
    ["cessio", "Forderungsabtretung"],
    ["circumscriptio", "Übervorteilung"],
    ["civis", "der (römische) Bürger"],
    ["clientes", "Hörige, Schutzbefohlene"],
    ["coactio non est imputabilis", "Zwang ist nicht zurechenbar"],
    ["codex", "Gesetzbuch, Gesetzessammlung"],
    ["cogitationis poenam nemo patitur", "wegen bloßer Gedanken wird niemand bestraft"],
    ["cognatio", "Blutsverwandtschaft, Kognation"],
    ["cognitio", "Erkenntnis"],
    ["collatio bonorum", "Einbringung es Vermögens"],
    ["collatio dotis", "Einbringung der Mitgift"],
    ["color insaniae", "Anschein des Wahnsinns"],
    ["commercium", "Rechtsverkehr, Handel"],
    ["commixtio", "Vermengen von festen Stoffen"],
    ["commodatum", "Leihe, Leihvertrag"],
    ["commodum", "Nutzen, Vorteil"],
    ["communio", "Gemeinschaft"],
    ["communis opinio", "(allgemein) herrschende Meinung"],
    ["communis opinio facit ius", "die übereinstimmende Meinung schafft Recht"],
    ["compensatio", "Aufrechnung, Kompensation, Abrechnung, Ausgleichung"],
    ["compromissum", "Schiedsvertrag"],
    ["concilium repraesentat mentem populi", "die Versammlung (der Abgeordneten) vertritt den Wille des Volkes"],
    ["concilium", "Versammlung"],
    ["conclusio", "logischer Schluss/ logische Schlussfolgerung"],
    ["condemnatio pecuniaria", "Geldverurteilung"],
    ["condemnatio", "Verurteilung"],
    ["condicio iuris", "Rechtsbedingung"],
    ["condicio pendet", "die Bedingung 'schwebt'/ die Bedingung 'hängt'"],
    ["condicio sine qua non", "'Bedingung ohne die nicht'"],
    ["condictio causa data causa non secuta",
     "Rückforderung wegen Nichteintreffens des Rechtsgrundes, auf den hin geleistet wurde"],
    ["condictio indebiti", "Rückforderung des Ungeschuldeten"],
    ["condictio liberationis", "Klage auf die Befreiung von einer Verpflichtung"],
    ["condictio ob causam finitam", "Rückforderung wegen Wegfall des Rechtsgrundes"],
    ["condictio ob iniustam causam", "Rückforderung wegen eines rechtswidrigen Grundes"],
    ["condictio ob turpem causam", "Rückforderung wegen eines sittenwidrigen Grundes"],
    ["condictio possessionis", "Klage auf Rückübertragung des Besitzes"],
    ["condictio sine causam", "Rückforderung 'ohne Grund'"],
    ["condictio", "Rückforderung"],
    ["condominium", "Miteigentum"],
    ["confessio est regina probationum", "das Geständnis ist die Königin der Beweismittel"],
    ["confessio non est probatio", "ein Geständnis ist kein Beweis"],
    ["confessio pro veritate accipitur", "das Geständnis wird als Wahrheit angesehen"],
    ["confessio", "Geständnis, Anerkennung"],
    ["confessus pro iudicator habetur", "der Geständige wird für verurteilt gehalten"],
    ["confirmatio", "Bestätigung"],
    ["confusio", "Vereinigung, Vermischung"],
    ["consensu contractur", "durch Willensübereinstimmung geschlossen"],
    ["consensus facit nuptias", "die Willensübereinstimmung schafft die Ehe"],
    ["consensus", "Willensübereinstimmung"],
    ["consilium", "Überlegung, Ratschlag, Rat (als Kollegium)"],
    ["consortium", "(Erben-)Gemeinschaft"],
    ["constitutum possessorium", "Besitzkonstitut"],
    ["constitutum", "Verabredung, Verfügung, Verordnung"],
    ["consuetudo", "Gewohnheit/ Gewohnheitsrecht"],
    ["consultum", "Beschluss (vom Senat) 'Rat'"],
    ["contra", "gegen, anderer Meinung"],
    ["contra bonos mores", "gegen die guten Sitten"],
    ["contra facta non valent argumenta", "gegenüber vorliegenden Tatsachen vermögen Argumente nichts"],
    ["contra legem", "gegen das Gesetz"],
    ["contra rem iudicatam nemo audietur", "nach Rechtskraft der Sache wird niemand mehr gehört werden"],
    ["contra vim non valet ius", "gegen Gewalt hat das Recht keine Macht"],
    ["contractus bilaterales aequales", "Vollkommen zweiseitiger Vertrag, synallagmatischer Vertrag"],
    ["contractus bilaterales inaequales", "unvollkommen zweiseitiges Schuldverhältnis"],
    ["contractus",
     "Vereinbarung, Vertrag, insb. Schuldvertrag (ein auf Begründung einer Verpflichtung gerichtetes Verhalten)"],
    ["contradictio in se", "Widerspruch in sich"],
    ["contradictio", "Widerspruch"],
    ["contrariam probationem non admittens", "den Gegenbeweis nicht zulassend"],
    ["contrarius actus", "Rechtsakt, der einen früheren aufhebt; Gegenteilige Handlung"],
    ["conubium", "das Recht, eine gültige römische Ehe einzugehen"],
    ["convalescentia", "Heilung (Gültigwerden eines bisher ungültigen Rechtsgeschäfts)"],
    ["conventio", "Übereinkunft, Abmachung, Vertrag, Konvention"],
    ["corpore et animo", "durch Gewahrsam und Besitzwillen"],
    ["corpus delicti", "Gegenstand des Verbrechens/ Beweisstück"],
    ["corpus", "Körper/ Gesamtheit von Werken"],
    ["creditor", "Gläubiger"],
    ["creditum", "Schuld, Darlehen"],
    ["cretio", "förmliche Erklärung, die Erbschaft antreten zu wollen"],
    ["crimen laesae maiestatis", "Verbrechen der verletzten Hoheit (Majestätsbeleidigung)"],
    ["crimen", "Verbrechen"],
    ["cui bono", "Wem zum Guten? Wem zum Vorteil? Wem zum Nutzen?"],
    ["cuius est commodum eius est incommodum", "wer den Vorteil hat, trägt auch die Last"],
    ["cuius est solum, eius est usque ad coelum", "wem der Boden gehört, dem gehört er bis zum Himmel"],
    ["cupla in contrahendo", "Verschulen bei Vertragschluss, insb. auch bei der Vertragsvorbereitung"],
    ["cupla lata", "schwere (grobe) Fahrlässigkeit"],
    ["culpa lata dolo proxima est", "grobe Farhlässigkeit kommt dem Vorsatz nahe"],
    ["culpa levis", "leichte Fahrlässigkeit"],
    ["culpa", "Verschulden (ganz allgemeint), Fahrlässigkeit"],
    ["cum tempore (c.t.)", "mit sog. 'akademischem Viertel' (mit Zeit)"],
    ["cura furiosi", "Pflegegewalt über den Geisteskranken"],
    ["cura minorum", "Pflegschaft über den Minderjährigen (den noch nicht 25-Jährigen)"],
    ["cura prodigi", "Verschwenderpflegschaft"],
    ["curator absentis", "Abwesenheitskurator"],
    ["curator bonorum", "Vermögensverwalter für die Konkursmasse"],
    ["curator", "Pfleger, Beistand, Verwalter, Sachwalter"],
    ["custodia", "Obhut, Gewahrsam, Aufsicht"],
    ["da mihi facta, dabo tibi uis", "liefere mir die Tatsachen, dann werde ich dir das Recht geben"],
    ["damnum emergens", "der 'aufgetretene' Schaden, positiver Schaden, der objektive Nachteil des Geschädigten"],
    ["damnum iniuria datum", "Sachbeschädigung (wörtlich: widerrechtlich verursachter Schaden)"],
    ["damnum", "(Eintritt eines) Schaden, Nachteil, Sachbeschädigung"],
    ["dare (do - dedi - datum)", "geben = Eigentum verschaffen"],
    ["dare actionem", "Erteilung der Klage"],
    ["datio", "Leistung, Zuwendung von Eigentum, Hingabe, Eigentumsverschaffung"],
    ["de facto", "tatsächlich"],
    ["de iure", "von Rechts wegen"],
    ["de lege", "von Gesetzes wegen"],
    ["de lege ferenda", "vom zu schaffenden Gesetz aus, vom zu erlassenden Gesetz her, von der Rechtslage aus"],
    ["de lege lata", "vom erlassenen Gesetz her; von der Rechtslage, wie sie derzeit ist"],
    ["debere (debeo - debui - debitum)", "schulden"],
    ["debitor", "Schuldner"],
    ["debitum", "Schuld, Verpflichtung"],
    ["declaratio", "Kundmachung, Offenbarung"],
    ["debitio", "Auslieferung (an den Feind)"],
    ["defensio", "Verteidigung (vor Gericht)"],
    ["defensor", "Verteidiger"],
    ["deleatur", "es möge vernichtet, getilgt, weggestrichen werden"],
    ["delegatio obligandi", "Verpflichtungsanweisung"],
    ["delegatio solvendi", "Zahlungsanweisung"],
    ["delegatio", "(bloße) Anweisung"],
    ["delictum", "unerlaubte Handlung, Vergehen, Fehler"],
    ["demonstratio", "Bezeichnung, Hinweis, Darlegung"],
    ["denegatio actionis", "Abweisung der Klage"],
    ["denuntiatio", "Anzeige, Ankündigung"],
    ["depositum", "'das Niedergelegte', Hinterlegunsvertrag, Verwahrungsvertrag"],
    ["derelictio",
     "Preisgabe, Weggabe (z.B. freiweillige Aufgabe des Eigentums an einer Sache ohne dass ein anderer Eigentümer wird)"],
    ["detentio", "Innehabung einer Sache"],
    ["dicat testaro et erit lex", "der Testator spreche und es wird Gesetz sein"],
    ["dicitur", "es wird gesagt, man sagt es, man behauptet es"],
    ["dicta et promissa", "Zugesagtes und Verprochenes"],
    ["dictum", "Spruch, Ausspruch, Wort"],
    ["dies cedens", "'Anfalltag' des Legats (= Todestag des Erblassers)"],
    ["dies veniens", "'der kommende Tag' (= Erfüllungs-, Zahltag des Legats - Fälligkeitstag)"],
    ["dies", "Tag, Termin, Frist, Befristung"],
    ["diligens paterfamilias", "sorgfältiger Hausvater"],
    ["diligentia", "Sorgfalt"],
    ["discrepantia", "Uneinigkeit, Widerspruch"],
    ["dismembratio", "Zerfall, Auflösung, Staatsuntergang durch Zerfall"],
    ["dispens", "Nachsicht, Befreiung"],
    ["dispositio", "Anordnung"],
    ["dissensus", "Meinungsverschiedenheit, Dissens, Uneinigkeit (Nichtübereinstimmung zweier Willenserklärungen)"],
    ["dissolutio", "Auflösung"],
    ["distinctio iuris", "Unterscheidung im Recht"],
    ["diversitas", "Verschiedenheit"],
    ["divortium", "Trennung, Scheidung"],
    ["do, ut des", "ich gebe (etwas), damit du (etwas) gibst"],
    ["doli capax", "deliktsfähigkeit"],
    ["dolo malo", "vorsätzlich, mit Arglist"],
    ["dolus directus", "direkter Vorsatz"],
    ["dolus eventualis", "bedingter Vorsatz"],
    ["dolus generalis", "allgemeiner Vorsatz"],
    ["dolus in contrahendo", "Arglist beim Vertragsschluss"],
    ["dolus malus", "böswilliger Vorsatz"],
    ["dolus non praesumitur", "Vorsatz wird nicht vermutet"],
    ["dolus pro passessione est", "die Arglist steht für den Besitz"],
    ["dolus semper praestatur", "für Vorsatz ist immer einzustehen"],
    ["dolus specialis", "besonderer Vorsatz (Wissentlichkeit)"],
    ["dolus suus neminem relevat", "niemandem hilft seine Arglist"],
    ["dolus", "die Arglist iSv Betrug (bewusste Täuschung, Schädigungsabsicht, der Vorsatz)"],
    ["domicilium", "Wohnsitz"],
    ["domini loco", "an Stelle des Eigentümers"],
    ["dominium directum", "Herrschaftsrecht (das umfassendste dingliche Recht)"],
    ["dominium transferre", "Eigentum übertragen"],
    ["dominium", "Eigentum"],
    ["dominius", "Herr, Eigentümer"],
    ["donatio", "Schenkung(-svertrag)"],
    ["dos, dotis f.", "Mitgift, Heiratsgut"],
    ["dotis dictio", "Zusage der Mitgift"],
    ["dotis promissio", "Versprechen, eine Mitgift zu bestellen"],
    ["dubium", "Zweifel"],
    ["duplicatio", "Entgegnung des Beklagten"],
    ["duplum", "das Doppelte"],
    ["eadem causa", "dieselbe Sache, derselbe Rechtsgrund, dieselbe Rechtsangelegenheit"],
    ["edictum", "Erlass, Bekanntmachung, Verordnung"],
    ["emancipatio", "Entlassung aus der Familiengewalt"],
    ["emptio spei", "'Kauf einer Hoffnung' (Hoffnungskauf/ Kauf einer bloßen Gewinnaussicht)"],
    ["emptio venditio", "Kaufvertrag"],
    ["emptor", "der Käufer"],
    ["errantis vuluntas nulla est", "der Wille eines irrenden ist nichtig"],
    ["error calculi non nocet", "ein Rechenfehler schadet nicht (z.B. im Urteil)"],
    ["error facti", "Irrtum über Tatsächliches"],
    ["error in corpore", "Irrtum in Bezug auf den Vertragsgegenstand"],
    ["error in iudicando", "Entscheidungsfehler"],
    ["error in negotio", "Irrtum über das Rechtsgeschäft, den Vertragstypus"],
    ["error in persona vel obiecto", "Irrtum in der Person oder im Vertragsgegenstand"],
    ["error in procedendo", "Verfahrensfehler"],
    ["error iuris", "Rechtsirrtum = Irrtum über Rechtsvorschriften"],
    ["error iuris nocet", "Irrtum über das Recht schadet"],
    ["error iuris nulli prodest", "ein Rechtsirrtum nützt niemandem"],
    ["error", "Irrtum, Fehler"],
    ["essentialia negotii", "die wesentlichen (und unentbehrlichen) Bestandteile eines Rechtsgeschäfts"],
    ["etiam tacere est respondere", "auch Schweigen ist eine Antwort"],
    ["evictio",
     "Entwehrung (Verkäufer haftet, wenn ein an der Kaufsache berechtigter Dritter diese vom Käufer herausverlangt)"],
    ["ex aequo et bono", "nach billigem und gutem (Ermesse)"],
    ["ex alia causa", "aus einem anderen Rechtsgrund"],
    ["ex ante", "von früher aus"],
    ["ex bona fide", "in gutem Glauben"],
    ["ex contractu", "auf einem Vertrage beruhend"],
    ["ex delicto", "aus einem begangenen Delikt"],
    ["ex eadem causa", "aus demselben Grund"],
    ["ex facto oritur ius", "Recht entsteht aus Tatsächlichem"],
    ["ex iniuria ius non oritur", "aus Unrecht kann kein Recht erwachsen"],
    ["ex lege", "unmittelbar auf das Gesetz zurückgehend"],
    ["ex nihilo nihil", "aus nichts kommt nichts"],
    ["ex nunc", "von jetzt an"],
    ["ex officio", "von Amts wegen"],
    ["ex pacto illicito non oritur actio", "aus einer unerlaubten Vereinbarung entsteht keine Klage"],
    ["ex post", "danach"],
    ["ex ratione legis", "nach dem Sinn des Gesetzes, aus der Sicht des Gesetzgebers heraus"],
    ["ex testamento", "aus dem Testament (als Berufungsgrund zu einem Erwerb)"],
    ["ex tunc", "vom damaligen Zeitpunkt an"],
    ["ex turpi causa non oritur actio", "aus einer verwerflichen Sache entsteht keine Klage"],
    ["exceptio doli", "Einrede des Arglist"],
    ["exceptio iusti dominii", "Einrede des rechtmäßigen Eigentums"],
    ["exceptio pacti", "Einrede der Vereinbarung des Nichtklagens"],
    ["exceptio plurium (concumbentium)",
     "Einrede des Mehrverkehrs während der Empfängniszeit (gegen eine Vaterschaftsklage)"],
    ["exceptio rei iudicatae", "Einrede der entschiedenen Sache"],
    ["exceptio rei venditae et traditae", "Einrede der verkauften und übergebenen Sache"],
    ["exceptio", "Einrede, Einwendung (eigentlich: Ausnahme)"],
    ["excusatio", "Entschuldigung"],
    ["executio iuris non habet iniuriam", "die Vollstreckung des Rechts ist kein Unrecht"],
    ["exempli causa", "beispielhalber"],
    ["exheredatio", "Enterbung eines Pflichtteilsberechtigten"],
    ["exilium", "Verbannung, Exil"],
    ["expressis verbis", "ausdrücklich"],
    ["extra", "außerhalb"],
    ["extraneus", "außenstehende Person"],
    ["facio, ut des", "ich mache (etwas), damit du (etwas) gibst"],
    ["facta concludentia",
     "schlüssige Handlungen, dh Handlungen, aus denen man eine bestimmte Willenserklärung ableiten kann"],
    ["factum", "Tat, Tatsache"],
    ["facultas", "Fähigkeit, Befähigung"],
    ["falsa demonstratio non nocet", "die Falschbezeichnung schadet nicht"],
    ["falsus procurator", "Vertreter ohne Vertretungsbefugnis"],
    ["fama", "Gerücht"],
    ["familia", "Familie (Gemeinschaft der Personen unter einer Hausgewalt)"],
    ["fas", "göttliches Recht"],
    ["favor", "Begünstigung"],
    ["fictio", "Fiktion, Annahme"],
    ["fictus possessor", "fingierter (angenommener) Besitzer"],
    ["fideiussio", "Bürgschaft"],
    ["fideiussor pro reo solvet", "der Bürger zahlt für den Schuldner"],
    ["fidepromissio", "Treueversprechen"],
    ["fides", "Treue, Glaube, Pflicht zum Wohlverhalten"],
    ["fiducia", "Vertrauen, Treuhand"],
    ["filiae familias", "die Töchter"],
    ["filii familias", "die Söhne"],
    ["fiscus", "Staatsvermögen"],
    ["forensis", "gerichtlich"],
    ["formaliter", "der Form nach / förmlich"],
    ["formula actionis", "Klagsformel"],
    ["forum commune", "allgemeiner Gerichtsstand"],
    ["forum contractus", "Gerichtsstand des Vertragsabschlussortes"],
    ["forum domicilii", "Gerichtsstand des Wohnsitzes des Beklagten"],
    ["forum prorogatum", "der verschobene Gerichtsstand"],
    ["forum", "öffentlicher Platz in Rom für Versammlungen und Gerichtsverhandlungen"],
    ["fraus creditorum", "Schädigung der Gläubiger"],
    ["fraus, fraudis", "Betrug / Gläubigerbenachteiligung im Konkurs"],
    ["fructus", "Frucht, Ertrag, Nutzen (auch: Gewinn, Vorteil, Lohn, Erfolg, Genuss)"],
    ["fundus", "Landgut, Grund und Boden"],
    ["fur semper in mora", "der Dieb befindet sich immer in Verzug"],
    ["fur", "Dieb"],
    ["furiosi voluntas nulla est", "der Wille eines Geisteskranken ist nichtig"],
    ["furiosus nullum negotium gerere potest", "der Geisteskranke kann kein Rechtsgeschäft führen"],
    ["furtum manifestum", "der offensichtliche Diebstahl"],
    ["furtum nec manifestum", "der nicht offensichtliche Diebstahl"],
    ["furtum possessionis", "Besitzdiebstahl"],
    ["furtum usus", "Gebrauchsdiebstahl"],
    ["furtum", "Diebstahl, Entwendung"],
    ["gens, gentis", "Sippe(-nverband), Großfamilie"],
    ["genus non perit", "die Gattung geht nicht unter"],
    ["genus", "Gattung, Art"],
    ["gestio", "Führung, Geschäftsführung, Verwaltung"],
    ["gradus", "Schritt, Stufe, Rang"],
    ["gratia", "Anmut, Gunst, Gefälligkeit"],
    ["gravitas", "Schwere, Gewicht, Last"],
    ["habitus", "Haltung, Stellung"],
    ["heredis institutio", "Erbeinsetzung"],
    ["hereditas iacens", "ruhender Nachlass"],
    ["hereditas", "Erbschaft"],
    ["hereditatis petitio", "Erbschaftsklage"],
    ["heres, heredis", "Erbe"],
    ["hic", "hier"],
    ["hic ec nunc", "hier und jetzt"],
    ["hic, haec, hoc", "dieser, dieses, dieses"],
    ["hoc loco", "an diesem Ort"],
    ["homicidium", "Mord, Totschlag"],
    ["homo", "Mensch"],
    ["honeste vivere, neminem laedere, suum cuique tribuere",
     "ehrenhaft leben, niemanden verletzen und jedem das Seine gewähren (das sind die Gebote des Rechts)"],
    ["honor", "Ehre"],
    ["hora", "Stunde"],
    ["humanitas", "Menschlichkeit"],
    ["humus", "Erde, Boden"],
    ["hypotheca", "besitzloses Pfand"],
    ["id est", "das heißt"],
    ["ignorantia facti, non iuris excusat", "Tatsachenunkenntnis, nicht Rechtsunkenntnis entschuldigt"],
    ["ignorantia iuris", "Rechtsunkenntnis"],
    ["ignorantia iuris nocet", "Unkenntnis des Rechts schadet"],
    ["ignorantia", "Unkenntnis / Unwissenheit"],
    ["immissio", "störende Einwirkung von außen auf ein Grundstück"],
    ["immobilis", "unbeweglich"],
    ["impensae necessariae", "notwendige Aufwendungen"],
    ["impensae utiles", "nützliche Aufwendungen"],
    ["imperator", "Feldherr / Befehlshaber"],
    ["imperitia iuris", "Unerfahrenheit im Recht"],
    ["imperitia", "unerfahrenheit / Ungeschicklichkeit"],
    ["imperium", "Macht / Staatsgewalt / Befehl"],
    ["impuberes infantia maiores", "noch nicht Mündige, die der Kindheit aber schon entwachsen sind"],
    ["in absentia", "in Abwesenheit"],
    ["in abstracto", "im Allgemeinen, abgesehen von der Wirklichkeit"],
    ["in brevi", "in Kürze"],
    ["in casu", "im gegebenen Fall"],
    ["in concreto", "in Wirklichkeit, im Besonderen"],
    ["in dubio contra actorem", "im Zweifelsfall gegen den Kläger"],
    ["in dubio minus", "im Zweifel weniger"],
    ["in dubio pro possesore", "im Zweifel für den Besitzer"],
    ["in dubio pro reo", "im Zweifel für den Angeklagten"],
    ["in effectu", "in der Wirkung, im Ergebnis"],
    ["in eventu", "möglicherweise / eventuell"],
    ["in flagranti", "auf frischer Tat"],
    ["in fraudem creditorum", "zum Schaden der Gläubiger"],
    ["in fraudem legis", "unter Umgehung des Gesetzes"],
    ["in futuro", "in Hinkunft, in Zukunft"],
    ["in iure", "vor Gericht / auf der Gerichtsstätte"],
    ["in iure cessio", "die Abtretung vor Gericht (Eigentumsübertragunsform des römischen Rechts)"],
    ["in ius vocatio", "Ladung zum Gericht"],
    ["in natura", "wirklich"],
    ["in perpetuum", "für ewig, für immer"],
    ["in praxi", "im Alltag / in der Praxis"],
    ["in rem versio", "Vermögensvermehrung, Bereicherung"],
    ["in solidum", "in Bezug auf das Ganze"],
    ["in status nascendi", "im Zustand des Entstehens"],
    ["in toto", "gesamt / gänzlich"],
    ["incapacitas", "Unfähigkeit"],
    ["incertum", "das Unbestimmte"],
    ["indebitum", "etwas Nichtgeschuldetes"],
    ["indebitum solutum", "Zahlung einer Nichtschuld"],
    ["indebitum, -i n.", "Nichtschuld"],
    ["infamia", "Schande, Ehrenlosigkeit, Ehrverlust"],
    ["infans, infantes", "Kind (bis 7 Jahre)"],
    ["infitiando lis crescit in duplum", "durch Bestreiten wächst die Haftsummer auf das Doppelte"],
    ["iniuria non excusat iniuriam", "Unrecht entschuldigt Unrecht nicht"],
    ["iniuria", "Unrecht, Beleidigung, Rechtswidrigkeit, Verstoß gegen die Rechtsordnung"],
    ["iniusta possessio", "unrecht, fehlerhafter Besitz"],
    ["iniustus possessor", "unrechter Besitzer (wer vi, clam oder precario besitzt)"],
    ["instrumenta dotalia", "Mitgifturkunden"],
    ["instrumenta probationis", "Beweismittel"],
    ["instrumenta sceleris", "Verbrechenswerkzeug"],
    ["instrumentum fundi", "Inventar eines Landgutes"],
    ["instrumentum", "Werkzeug/ Zubehör zu einem Laden oder Grundstück / Ukrunde über ein Rechtsgeschäft"],
    ["intentio", "Absicht, Rechtsbehauptung, Klagebegehren (vgl heute: Intention)"],
    ["inter", "zwischen"],
    ["inter absentes", "unter Abwesenden, gegenüber Abwesenden"],
    ["inter partes", "unter den Parteien"],
    ["inter vivos", "unter Lebenden"],
    ["intercessio", "Übernahme der Haftung für eine fremde Schuld, zB Bürgschaft"],
    ["interdictio", "Entmündigung (eigentlich: Verbot)"],
    ["interdictum demolitorium", "Interdikt zur Beseitigung des Baus"],
    ["interdictum uti possidetis", "Interdikt 'wie ihr besitzt' (zum Schutz des Besitzes an Grundstücken)"],
    ["interdictum utrubi", "Interdikt 'bei wem von beiden' (zum Schutz des Besitzes an beweglichen Sachen)"],
    ["interpretatio extensiva", "ausdehnende Auslegung"],
    ["interpretatio legalis", "Auslegung durch das Gesetz (Legalinterpretation)"],
    ["interpretatio restrictiva", "einschränkende Auslegung"],
    ["interpretatio", "Auslegung"],
    ["interrogatio", "Befragung, Verhör"],
    ["invecta et illata", "die vom Pächter oder Mieter eingebrachten Sachen"],
    ["inventarium", "Verzeichnis der Erbschaftsgegenstände"],
    ["invitatio ad offerendum", "Aufforderung zur Abgabe eines Anbots"],
    ["invito beneficium non datur", "eine Rechtswohltat kann niemandem gegen seinen Willen aufgedrängt werden"],
    ["invitus agere nemo cogitur", "niemand wird gegen seinen Willen gezwungen, eine Klage einzubringen"],
    ["ipso facto", "durch dieselbe Tat"],
    ["ipso iure", "Unmittelbar kraft Rechtssatzes"],
    ["is damnum dat qui iubet dare", "derjenige fügt den Schaden zu, der ihn zuzufügen anordnet"],
    ["iter", "Weg, Wegerecht"],
    ["iudex inhabilis", "untauglicher Richter"],
    ["iudex iudicet secundum allegata et probata patrium",
     "der Richter möge gemäß dem von den Parteien Vorgebrachten und Bewiesenen urteilen"],
    ["iudex ne procedat ex officio", "der Richter soll nicht von Amts wegen einen Prozess einleiten"],
    ["iudex non calculat", "der Richter rechnet nicht"],
    ["iudex suspectus", "verdächtiger Richter (heute: befangener Richter)"],
    ["iudex unus", "Einzelrichter"],
    ["iudex", "Richter"],
    ["iudicatum", "Urteil(sschuld)"],
    ["iudicia stricti iuris", "Verfahren mit kaum Ermessensspielraum des Richters (wörtl.: strengrechtliche Klage)"],
    ["iudicium rescindens", "aufhebendes Verfahren"],
    ["iudicium rescissorium", "Erneureungsverfahren"],
    ["iudicium", "Urteilsspruch, gerichtliche Entscheidung, Rechtsstreit"],
    ["iura in re aliena", "Recht an fremder Sache (heute: beschränkte dingliche Rechte)"],
    ["iura novit curia", "die Kurie (das Gericht) kennt das Recht"],
    ["iura praediorum", "Grunddienstbarkeiten (Realservituten)"],
    ["iura praediorum rusticorum", "Recht an ländlichen Grundstücken oder Feldservituten"],
    ["iura praediorum urbanorum", "Recht an städtischen Grundstücken oder Gebäudeservituten"],
    ["iure suo uti nemo cogitur", "niemand ist verpflichtet, von dem ihm zustehenden Recht Gebraucht zu machen"],
    ["iuris ignorantia nocet, facti non nocet",
     "Unkenntnis des Gesetzes schadet, Unkenntnis von Tatsachen jedoch nicht"],
    ["iurisdictio", "Gerichtsbarkeit"],
    ["iurisprudentia", "Rechtswissenschaft / Rechtssprechung"],
    ["ius cogens", "zwingendes Recht"],
    ["ius commune", "gemeines Recht"],
    ["ius dispositivum", "nachgiebiges Recht"],
    ["ius gentium", "Völkerrecht"],
    ["ius non scriptum", "ungeschriebenes Recht (zB Gewohnheitsrecht)"],
    ["ius offerendi et succedendi", "Recht des Anbietens und Nachfolgens"],
    ["ius positivum", "gesetztes (= aufgrund menschlichen Willens geschaffenes) Recht"],
    ["ius privatum", "Privatrecht"],
    ["ius privatum sub tutela iuris publici latet", "das Privatrecht steht unter der Obhut des öffentlichen Rechts"],
    ["ius publicum", "öffentliches Recht"],
    ["ius publicum privatorum pactis mutari non potest",
     "Öffentliches Recht kann durch Vereinbarungen Privater nicht geändert werden"],
    ["ius puniende", "das Recht zu strafen"],
    ["ius", "Recht, Rechtsordnung, Berechtigung"],
    ["iusiurandum in iure", "Eid vor Gericht"],
    ["iusiurandum in litem", "Schätzungseid"],
    ["iusiurandum", "Eid"],
    ["iussum", "Befehl, Gebot, Ermächtigung"],
    ["iusta causa", "gültiger, tauglicher Rechtsgrund"],
    ["iusta causa possessionis", "Erwerbstitel (wörtl.: einen rechtsmäßigen Grund für den Besitz)"],
    ["iustitia", "Gerechtigkeit, Rechtspflege"],
    ["lacuna iuris", "Rechtslücke"],
    ["lacuna", "Lücke, Öffnung, Loch"],
    ["laesio enormis", "Verkürzung über die Hälfte ('übermäßig große' Verletzung)"],
    ["laesio", "absichtliche Verletzung, Nachteil"],
    ["latu sensu", "im Weiten, im weiteren Sinn"],
    ["legatum debiti", "Erfüllung einer schon bestehenden Schuld durch Legat"],
    ["legatum per damnationem",
     "Damnationslegat ('Legat druch Verpflichtung'; den Erben trifft eine Schuldrechtliche Verpflichtung auf Erfüllung des Vermächtnisses)"],
    ["legatum per vindicationem",
     "Vindikationslegat (Dinglich wirkendes Legat, bei dem der Bedachte ipso iure ein dingliches Recht erhält und dieses gegen den Erben mit der entsprechenden vindicatio durchsetzen kann)"],
    ["legatum", "Vermächtnis (nicht Erbschaft!)"],
    ["legem ferre", "ein Gesetz erlassen"],
    ["legis citatae", "das zitierte Gesetz"],
    ["legislatio", "Gesetzgebung"],
    ["legislator", "Gesetzgeber"],
    ["legitimatio ad causam activa", "Aktivlegitimation (Befugnis, als Kläger aufzutreten)"],
    ["legitimatio ad causam passiva", "Passivlegitimation (Stellung als Beklagter)"],
    ["levis nota", "kleiner Makel"],
    ["lex commissoria", "Verfallsklausel, Verwirkungsklausel (im röm. Kauf- und Pfandrecht"],
    ["lex contractus", "Vertragsklausel"],
    ["lex imperfecta", "unvollkommenes Gestz (darunter versteht man ein sanktionsloses Gesetz)"],
    ["lex iniusta non est lex", "ein ungerechtes Gesetz ist kein Gesetz"],
    ["lex perfecta", "vollkommenes Gestz (es sieht für den Fall von Zuwiderhandlungen eine wirksame Sanktion vor)"],
    ["lex posterior derogat priori", "das spätere Gesetz setzt das frühere außer Kraft"],
    ["lex prospicit, non respicit",
     "das Gesetz blickt vorwärts, nicht rückwärts (Gesetze haben keine rückwirkende Kraft)"],
    ["lex rei sitae",
     "das Gesetz der gelegenen Sache (Grundsatz, wonach zivilrechtlich im Allgemeinen das Gesetz des Ortes maßgeblich ist, in welchem die streitverfangene Sache liegt)"],
    ["lex scripta", "geschriebenes Gesetz (im Gegensatz zum ungeschriebenen Gewohnheitsrecht)"],
    ["lex specialis derogati generali", "das besondere Gesetz hebt das allgemeine auf"],
    ["lex superior derogat inferiori", "das übergeordnete Gesetz hebt das untergeordnete auf"],
    ["lex, legis", "Gesetz, Klausel"],
    ["liber", "Buch, Schrift"],
    ["liberatio", "Befreiung"],
    ["liberi", "(Haus)Kinder / Freie"],
    ["libertas", "Freiheit, Stand des Freigelassenen"],
    ["libra", "Waage"],
    ["licentia", "Erlaubnis, Freiheut, Ungebundenheit"],
    ["licet", "es ist erlaubt"],
    ["licitum", "das Erlaubte"],
    ["limen", "Grenze"],
    ["lis, litis f.", "Rechtsstreit"],
    ["litis aestimatio", "Schätzung des Streitgegenstandes"],
    ["litis contestatio", "Streitbefestigung, Streitbezeugung, Streiteinsetzung"],
    ["litis denuntiatio", "Streitverkündigung"],
    ["littera", "Buchstabe, Brief, Wissenschaft"],
    ["locatio conductio operarum", "Dienstvertrag"],
    ["locatio conductio operis", "Werkvertrag"],
    ["locatio conductio rei", "Mietvertrag, Pachtvertrag, Miete, Pacht, Bestandsvertrag"],
    ["locus regit actum", "der Ort bestimmt das Geschehen"],
    ["locus", "Ort, Stelle"],
    ["lucida intervalla", "die 'lichten Momente' (zeitweilige Zurechnungsfähigkeit von an sich Geisteskranken)"],
    ["lucrum cessans", "entangener Gewinn"],
    ["lucrum", "Gewinn"],
    ["magister", "Meister, Lehrer"],
    ["magistratus", "römisches Staatsamt"],
    ["major dividat, minor eligat", "der Ältere möge teilen, der Jüngere sollte wählen"],
    ["mala fides", "Schlechtgläubigkeit, Unredlichkeit"],
    ["malae fidei possessor",
     "Besitzer 'schlechten Glaubens' bösgläubiger Besitzer: jemand, der weiß, dass ihm die Sache nicht gehört"],
    ["mancipatio",
     "'Handergreifung' (Förmliches Rechtsgeschäft aus dem älteren röm. Recht, durch das Rechte übertragen werden)"],
    ["mancipium", "Herrschaft/ Gewalt über Sachen"],
    ["mandatum morte solvitur", "der Auftragsvertrag erlischt mit dem Tod"],
    ["mandatum", "Auftrag, vertragliche Übernahme einer Geschäftsbesorgung"],
    ["manifesta non egent probatione", "was offenkundig ist, bedarf keines Beweises"],
    ["manumissio", "Freilassung / Entlassung aus der Gewalt"],
    ["manus manum lavat", "eine Hand wäscht die andere"],
    ["manus", "wört.: Hand, Hausgewalt im Allgemeinen (Gewalt (des pater familias) über die Ehefrau)"],
    ["mare liberum", "das freie Meer"],
    ["mater familias", "Ehrentitel der Mutter ehelicher Kinder"],
    ["mater semper certa est", "die Mutter ist immer gewiss"],
    ["matrimonium consummatum", "die (durch Beischlaft) vollzogene Ehe"],
    ["matrimonium", "die Ehe"],
    ["mens testatoris", "Wille des Erblassers"],
    ["mens", "Verstand, Vernunft, Einsicht, Geist"],
    ["merx", "Ware, Kaufsache"],
    ["metus", "die Furcht"],
    ["minima non curat praetor", "um Geringfügigkeit kümmert sich der Prätor nicht"],
    ["minor viginta quinque annis", "der nocht nicht 25-jährige"],
    ["mobilia sequuntur personam", "bewegliche Sachen folgen der Person"],
    ["mobilia", "bewegliche Sachen"],
    ["modus operandi (procedendi)", "Vorgehensweise"],
    ["modus vivendi", "die Art und Weise, miteinander zu leben"],
    ["modus", "Art und Weise (zB. der rechtlichen Erwerbung)"],
    ["mora accipiendi", "Leistungsverzug"],
    ["mora creditoris", "Grläubigerverzug"],
    ["mora debitoris", "Schuldnerverzug"],
    ["mora perpetuatur obligatio", "durch Verzug wird die Obligation verewigt"],
    ["mora solvendi", "Annahmeverzug"],
    ["mora", "Verzug, Verzögerung, Aufschub"],
    ["mors certa, hora incerta est", "der Tod ist sicher, die Stunde (des Todes) ungewiss"],
    ["mors litis", "Erlöschen des Prozesses durch Ablauf seiner Befristung"],
    ["mors, mortis f.", "Tod"],
    ["mortis causa", "von Todes wegen"],
    ["mos maiorum", "Sitte der Vorfahren, Sitte der 'Älteren', Gewohnheitsrecht"],
    ["mos, moris m.", "Sitte, Brauch, Gewohnheit"],
    ["multa", "Geldbuße / Strafsumme"],
    ["mundus", "Welt, Erde"],
    ["municipium", "selbständige Stadtgemeinde"],
    ["mutuum", "Darlehen, Darlehensvertrag"],
    ["narra mihi factum dabo tibi ius", "erzähle mir den Sachverhalt und ich werde darüber Recht sprechen"],
    ["nasciturus", "die noch ungeborene Leibesfrucht; der Embryo"],
    ["nasciturus pro iam nato habetur, quotiens de commodis eius agitur",
     "die Leibesfrucht gilt als geboren, soweit es um ihre Vorteile geht"],
    ["naturalia negotii",
     "Regelungen, die auch ohne konkrete Vereinbarungen der Parteien eines Vertrages aufgrund der Rechtsornung Vertragsinhalt werden"],
    ["naturalis possessio", "natürlicher Besitz"],
    ["ne eat iudex ultra petita parium", "der Richter möge nicht über das Begehren der Parteien hinausgehen"],
    ["necessitas legem non habet", "die Notwendigkeit hat kein Gesetz"],
    ["necessitas", "Notwendigkeit"],
    ["nefas", "religiöses Unrecht, Frevel, Sünde"],
    ["negativa non sunt probanda", "das Nichtbestehen von Tatsachen braucht nicht bewiesen zu werden"],
    ["neglegentia crassa", "grobe Fahrlässigkeit"],
    ["negligentia", "Fahrlässigkeit, Nachlässigkeit"],
    ["negotiorum gestio", "Geschäftsführung ohne Auftrag 'Führung von (fremden) Geschäften'"],
    ["negotium gestor", "Geschäftsführung ohne Auftrag"],
    ["negotium bilaterale", "zweiseitiges Rechtsgeschäft"],
    ["negotium inter vivos", "Rechtsgeschäft unter Lebenden"],
    ["negotium mortis causa", "Rechtsgeschäft von Todes wegen"],
    ["negotium nullum / negotium imperfectum", "nichtiges Rechtsgeschäft"],
    ["negotium unilaterale", "einseitiges Rechtsgeschäft"],
    ["negotium", "Geschäft, Rechtsgeschäft (auch: Beschäftigung, Arbeit, Auftrag, Angelegenheit)"],
    ["nemo", "niemand"],
    ["nemo cum damno alterius locupletior fieri debet", "niemand darf sich zum Schaden eines anderen bereichern"],
    ["nemo iudex in sua causa", "niemand sei Richter in eigener Sache"],
    ["nemo iudex sine actore", "wo kein Kläger, da kein Richter (wörtl.: Niemand ist Richter ohne Kläger)"],
    ["nemo plus iuris ad alium transferre potest quam ipse habet",
     "niemand kann mehr Recht an einen anderen übertragen, als er selbst hat"],
    ["nemo prudens punit, quia peccatum est, sed ne peccetur",
     "niemand, der klug ist, straft, weil eine Verfehlung, begangen wurde, sondern damit in Hinkunft nicht mehr gefehlt wird"],
    ["nemo sibi ipse causam possessionis mutare potest",
     "niemand kann eigenmächtig seine Besitzposition zu seinen Gunsten verändern"],
    ["nemo tenetur se ipsum accusare",
     "der Beschuldigte kann nicht gezwungen werden, gegen sich selbst auszusagen (niemand kann dazu verhalten werden, sich selbst anzuklagen)"],
    ["nepos", " Geschwistersohn = Neffe, Enkel, Nachkomme"],
    ["nexum", "Haltungsgeschäft"],
    ["nolens volens", "nicht wollend (und doch) wollend"],
    ["nomen", "Name, Forderung"],
    ["non liquet", "es ist nicht klar"],
    ["non omne, quod licet, honestum est", "nicht alles, was erlaubt ist, ist auch ehrenhaft"],
    ["non sequitur", "es folgt nicht daraus (ein nicht schlüssiges Argument)"],
    ["nova causa supervenins", "neu hinzutretender Rechtsgrund"],
    ["nova producta", "neu Hervorgebrachtes / neu Erzeugtes"],
    ["nova reperta", "neu Ermitteltes / neu Entdecktes"],
    ["novatio", "Neuerungsvertrag"],
    ["novum", "ein neuer Tatbestand / etwas Neues"],
    ["noxa", "Vergehen, Schädigung, Schaden, Schadenersatz"],
    ["noxae deitio", "Auslieferung des Schädigers (zum Ersatz des Schadens)"],
    ["nulla iniuria est, quae in volentem fiat",
     "eine Handlung stellt dann kein Unrecht dar, wenn sie sich gegen jemanden richtet, der mit ihr einverstanden ist"],
    ["nulla poena sine culpa", "keine Strafe ohne Schuld"],
    ["nulla poena sine lege", "keine Strafe ohne Gesetz"],
    ["nullum", "nichts"],
    ["nullum crimen sine lege", "kein Verbrechen ohne Gesetz"],
    ["nullus", "niemand"],
    ["numerus clausus", "geschlossene Zahl"],
    ["nuncupatio", "mündliche Erklärung oder Abmachung"],
    ["nuptiae", "Hochzeit, eheliche Verbindung, Verheiratung, Ehe"],
    ["obiter dictum", "nebenbei Gesagtes"],
    ["oblatio debiti", "das Anbieten des Geschuldeten"],
    ["obligatio ex delicto", "Deliktsschuld"],
    ["obligatio(new) ex contractu", "Vertragsschuld(en)"],
    ["obligatio", "Verbindlichkeit, Schuldverhältnis"],
    ["obligationes litteris contractae",
     "Litteralkontrakte - schriftliche Verträge (wörtl.: durch die Schrift geschlossene Verträge)"],
    ["occidere, occido1", "töten"],
    ["occupatio", "Aneignung herrenloser Sachen (wörtl.: Besetzung, Besitznahme, Inanspruchnahme)"],
    ["odium", "Hass"],
    ["omni modo facturus", "eine Person, die bereits zur Ausführung einer Tat entschlossen ist"],
    ["omnis definitio in iure civile periculosa est", "jede Definition im bürgerlichen Recht ist gefährlich"],
    ["omnis obligatio vel ex contractu nascitur vel ex delicto",
     "jede Verpflichtung wird entweder aus Vertrag oder aus Delikt geboren"],
    ["onus probandi", "Beweislast"],
    ["onus", "Last, Leistung, Beschwer"],
    ["opera", "Dienstleistung, Arbeit, Mühe"],
    ["opinio communis", "allgemeine Meinung, herrschende Auffassung"],
    ["opinio iuris", "Rechtsmeinung, Rechtsüberzeugung"],
    ["opinio", "Meinung, Überzeugung"],
    ["optimum", "das Beste"],
    ["optio", "Wahl, Möglichkeit"],
    ["opus", "Werk, Bauwerk"],
    ["oratio", "Sprache, Rede, Vortrag"],
    ["orbis", "Kreis, Umkreis, Erde, Welt"],
    ["origo", "Ursprung"],
    ["pacta sunt servanda", "Verträge sind einzuhalten"],
    ["pactum de non petendo", "(formlose) Abrede des Nichtklagens"],
    ["pactum de vendendo", "Verkaufsabrede"],
    ["pactum fiduciae", "Treuhandvereinbarung"],
    ["pactum in favorem tertii", "Vertrag zugunsten Dritter"],
    ["pactum legitimum", "gesetzliche Vereinbarung"],
    ["pactum tacitum", "stillschweigende Vereinbarung"],
    ["pactum", "Abrede, Abmachung (Formfreie Verträge außerhalb des klassischen Vertragsschemas)"],
    ["par", "gleich"],
    ["par condicio creditorum", "gleiche Stellung der Gläubiger im Konkursverfahren"],
    ["par in parem non habet imperium", "der Gleiche hat über den Gleichen keine Herrschaftsgewalt"],
    ["parens manumissor", "der freilassende Vater"],
    ["parentela", "Verwandtschaft"],
    ["pars pro toto", "ein Teil für das Ganze"],
    ["pars, partis f.", "Teil, Anteil, Partei"],
    ["partus ancillae", "das Kind einer Sklavin"],
    ["pater", "Vater"],
    ["patria potestas", "Hausgewalt (des pater familias) über die ehelichen Kinder und Kindeskinder"],
    ["patronus", "Schutzherr / Herr"],
    ["peculium", "Sondergut zur Bewirtschaftung, Sondervermögen (eines Sklaven oder auch eines Haussohnes)"],
    ["pecunia non olet", "Geld stinkt nicht"],
    ["pecunia", "Geld, Vermögen"],
    ["pecus", "Vieh"],
    ["pedente lite", "bei schwebendem Verfahren"],
    ["per analogiam", "durch Analogieschluss"],
    ["per definitionem", "durch die Definition"],
    ["per se", "an und für sich, von selbst"],
    ["peregrinus", "Nichtrömer, Fremder, der Nichtbürger"],
    ["perfidie", "Treulosigkeit, Hinterlistigkeit"],
    ["periculum eius esse debet, cuius est commodum", "die Gefahr soll der tragen, der den Vorteil hat"],
    ["periculum est emptoris", "die Gefahr trägt der Käufer"],
    ["periculum in mora", "Gefahr im Verzug"],
    ["periculum", "Gefahr / Gefahrtragung"],
    ["permutatio", "Tausch"],
    ["perpetua causa", "ständige Angelegenheit"],
    ["perpetuatio fori", "Beibehaltung des Gerichtsstandes"],
    ["perpetuatio obligationis",
     "Fortdauer der Verbindlichkeit (wenn die Erfüllung einer Forderung nachträglich unmöglich wird, kann die Forderung des Gläubigers als Schadenersatzansrpuch fortbestehen)"],
    ["perpetuus", "fortdauernd, fortgesetzt"],
    ["persona non grata", "unerwünschte Person"],
    ["persona sui iuris", "eigenberechtigte Person"],
    ["persona", "Person, Persönlichkeit"],
    ["petitio", "Bitte, Klagerecht, Gesuch, Klage, Anspruch"],
    ["pignus conventionale", "druch Vertrag begründetes Pfandrecht"],
    ["pignus datum", "Faustpfand ('das hingegebene Pfand')"],
    ["pignus hypotheca", "besitzloser Pfand"],
    ["pignus irregulare", "unregelmäßiges Pfand"],
    ["pignus legale", "gesetzliches Pfandrecht"],
    ["pignus pignore dari potest", "ein Pfand kann zum Pfand gegeben werden"],
    ["pignus", "Pfand, Pfandsache, Pfandgegenstand"],
    ["plebiscitum", "Volksbeschluss"],
    ["plebs", "Volk"],
    ["pleno iure", "mit vollem Recht"],
    ["pleno titulo", "mit vollem Titel"],
    ["plenum", "Vollversammlung, Gesamtheit"],
    ["plenus venter non studet libenter", "ein voller Bauch studiert nicht gern"],
    ["pluris petitio", "Mehrbegehren"],
    ["poena capitalis", "Todesstrafe"],
    ["poena maior absorbet minorem", "die höhere Strafe schließt die geringere Strafe in sich"],
    ["poena talionis", "Vergeltungsstrafe"],
    ["poena", "Strafe, Buße"],
    ["poenalia non sunt extendenda", "Strafsachen dürfen nicht ausgedehnt werden"],
    ["pontifex", "Oberpriester"],
    ["populus romanus", "das römische Volk"],
    ["portio debita", "der geschuldete Anteil"],
    ["possessio ad interdicta", "Interdiktenbesitz"],
    ["possessio ex iusta causa", "Besitz, der auf einem gültigen Erwerbstitel beruht"],
    ["possessio iuris", "Rechtsbesitz"],
    ["possessio iusta", "echter Besitz"],
    ["possessio non est iuris, sed facti", "der Besitz ist nicht eine Frage des Rechts, sondern der Tatsche"],
    ["possessio vitiosa", "fehlerhafter Besitz"],
    ["possessio", "Besitz"],
    ["possessor", "Besitzer"],
    ["post mortem", "nach dem Tod"],
    ["postulatio actionis", "Beantragung einer Klage"],
    ["potestas", "Macht, Amtsgewalt"],
    ["praedium", "Grundstück"],
    ["praes", "Bürge"],
    ["praescriptio", "Vorschrift, Verjährung"],
    ["praesumptio cedit veritati", "die Vermutung weicht gegenüber der Wahrheit"],
    ["praesumptio facti", "Tatsachenvermutung"],
    ["praesumptio iuris", "Rechtsvermutung"],
    ["praesumptio iuris et de iure", "unwiderlegbare Rechtsvermutung"],
    ["praesumptio", "Vermutung"],
    ["praeter legem", "außerhalb des Gesetzes"],
    ["precarium", "das Erbetene (freiwilige, jederzeit widerrufbare Überlassung einer Sache)"],
    ["pretium iustum", "der 'gerechte Preis'"],
    ["pretium", "Preis, Wert, 'Zins'"],
    ["prima facie", "auf den ersten Blick"],
    ["primo loco", "an erster Stelle"],
    ["primus", "der Vorderste, der Erste"],
    ["primus inter pares", "Erster unter Gleichen"],
    ["prior", "frühere"],
    ["prior tempore potior iure",
     "der zeitlich Frühere ist der rechtlich Stärkere (wörtl.: früher in der Zeit, stärker im Recht)"],
    ["prius", "das Vorhergehende"],
    ["privilegium personae", "Vorrecht bezüglich einer Person"],
    ["privilegium rei", "Vorrecht bezüglich einer Sache"],
    ["privilegium", "Sonderrecht, das dem einzelnen im Gegensatz zur Allgemeinheit verliehene Vorrecht"],
    ["pro", "vor, für, anstatt"],
    ["pro domo", "für das Haus, im eigenen Interesse"],
    ["pro forma", "zum Schein"],
    ["pro foro externo", "für die Öffentlichkeit bestimmt"],
    ["pro futuro", "für die Zukunft"],
    ["pro rata", "für einen Anteil"],
    ["probare debet, qui dicit, non qui negat", "beweisen muss, wer etwas sagt, nicht, wer etwas verneint"],
    ["probatio diabolica", "der 'teuflische' Beweis (Beweis der Vormännerkette bis zum originären Eigentumserwerb)"],
    ["probatio", "Beweis, Beweismittel, Billigung"],
    ["procuratio", "Verwaltung, Besorgung"],
    ["procurator",
     "Vermögensverwalter (im römischen Recht), Vertreter, Geschäftsführer, Prozessvertreter, Statthalter"],
    ["prodigus", "Verschwender"],
    ["producta sceleris", "Produkte (Ergebnisse) einer strafbaren Handlung"],
    ["professor", "einer, der sich öffentlich erklärt - Hochschullehrer"],
    ["promissio", "Versprechen"],
    ["pronuntiatio", "öffentliche Bekanntmachung"],
    ["proprietas", "Eigentum"],
    ["proprio nomine", "im eigenen Namen"],
    ["prorogatio fori", "Verlegung des Gerichtsstandes"],
    ["protestatio facto contrari non valet", "ein gegen Tatsachen widersprüchliches Erklärungsverhalten wirkt nicht"],
    ["protestatio", "Einspruch"],
    ["provocatio", "Berufung (gegen)"],
    ["pubertas", "Mündigkeit, Geschlechtsreife"],
    ["pubertati proximi", "Unmündige, die aber dem Alter der Mündigkeit schon nahe sind"],
    ["punitur ne peccetur", "es wird gestraft, damit kein Unrecht geschieht"],
    ["pupillus", "Unmündiger, der unter keiner Gewalt steht, Mündel, Pflegebefohlener, Waise"],
    ["quaestio facit", "Frage der Tatsache, Tatsachenfrage"],
    ["quaestio iuris", "Frage des Rechts, Rechtsfrage"],
    ["quaestio voluntatis", "Frage des Willens, Willensfrage"],
    ["quaestio", "Frage, Untersuchung / Gerichtshof für Verbrechen / Folter"],
    ["quam", "wie"],
    ["quanti ea res erit", "wieviel die Sache wert sein wird (bei Urteilsfällung)"],
    ["quanti ea res est", "wieviel die Sache wert ist (bei Prozessbeginn)"],
    ["quantus", "wieviel"],
    ["quasi", "gleichsam"],
    ["querela", "Beschwerde, Klage"],
    ["qui, quae, quod", "welcher? welche? welches?"],
    ["qui possidet dominus esse praesumitur",
     "wer eine Sache besitzt, von dem wird vermutet, dass er ihr Eigentümer sei"],
    ["qui suo iure utitur neminem laedit", "wer sein Recht ausübt, schädigt niemanden"],
    ["qui tacet consentire videtur", "wer schweigt, scheint zuzustimmen"],
    ["quidam", "ein gewisser, irgendein"],
    ["quisquis praesumitur bonus", "jeder wird als redlich vermutet"],
    ["quoad usum", "Übertragung eines Gebrauchsrechts"],
    ["quod erat demonstrandum", "was zu beweisen war"],
    ["quod licet lovi non licet bovi",
     "was Jupiter erlaubt ist, ist dem Ochsen nicht erlaubt (Ausdruck unterschiedlicher persönlicher Freiheiten je nach Status)"],
    ["quod non est in actis, non est in mundo", "was nicht in den Akten ist, ist nicht in der Welt"],
    ["quod non est licitum in lege necessitas facit licitum",
     "was durch Gesetz nicht erlaubt ist, macht die Not erlaubt"],
    ["quod sine die debetur statim debetur", "was ohne Termin geschuldet wird, wird sofort geschuldet"],
    ["quota litis", "Anteil am Streitgegenstand (Erfolgshonorar für den Anwalt)"],
    ["rapine", "Raub"],
    ["ratio legis", "Zweck des Gesetzes"],
    ["ratio naturalis", "die natürliche Vernunft"],
    ["ratio", "Rechnung, Rechenschaft, Grund, Zweck, Vernunft"],
    ["ratione loci", "aufgrund des Ortes"],
    ["ratione personae", "aufgrund der Person"],
    ["re extincta pignus perit", "das Pfand geht mit der Zerstörung der (Pfand-)Sache unter"],
    ["receptio", "Übernahme"],
    ["receptum", "Garantieübernahme, Garantie, Verpflichtung, Pflicht"],
    ["reformatio in peius", "Erneuerung zum Schlechteren"],
    ["regalia (pl)", "bestimmte Hoheitsrechte"],
    ["regressus", "Rückgriff"],
    ["regula iuris", "Rechtsregel"],
    ["rei vindicatio", "Eigentumsklage"],
    ["rem et poenam", "Klagsziel ist sowohl Schadenersatz als auch Strafe"],
    ["rem sibi non liquere", "sich über die Sache nicht klar sein"],
    ["remissio", "Erlass"],
    ["remotio tutoris", "Enthebung des Vormunds"],
    ["remuneratio", "Vergeltung, Erkenntlichkeit"],
    ["replicatio doli", "Gegeneinrede der Arglist"],
    ["replicatio", "Gegeneinrede"],
    ["reprobatio", "Gegenbeweis"],
    ["res (nec) mancipi", "(nicht) manzipationsfähige Sachen"],
    ["res certa", "eine bestimmte Sache"],
    ["res derelictae", "preisgegebene Sachen"],
    ["res extra commercium", "Sachen, die am Rechtsverkehr nicht teilnehmen"],
    ["res fungibiles", "vertretbare Sachen"],
    ["res furtivae", "gestohlene Sachen"],
    ["res habilis", "ersitzungsfähige Sachen"],
    ["res humani iuris", "Sachen menschlichen Rechts"],
    ["res in iudicium deducta", "prezessanhängige Sachen"],
    ["res iudicata", "rechtskräftig entschiedene Streitsache"],
    ["res iudicata ius faceit inter partes", "die rechtlich entschiedene Sache schafft Recht zwischen den Parteien"],
    ["res iudicata pro veritate accipitur", "die rechtlich entschiedene Sache wird für die Wahrheit gehalten"],
    ["res litigiosa", "streitverfangene Sache"],
    ["res nullius", "herrenlose Sache(n)"],
    ["res omnium communes", "Sachen, die allen gemeinsam gehören, Gemeingut"],
    ["res publica", "Gemeinwesen, Staat"],
    ["res quae usu consumuntur", "verbrauchbare Sachen"],
    ["res religosae", "regligiöse Sachen"],
    ["res sacrae", "den Göttern geweihte Sachen"],
    ["res sanctae", "unter göttlichem Schutz stehende Sachen"],
    ["res venalis", "käufliche Sache / Kaufsache"],
    ["res, rei f.",
     "Sache, Gegenstand, Ding (einzelne abgegrenzte, juristische selbständige, körperliche Sache. Alles, was Gegenstand (Rechtsobjekt) eines (privaten) Rechts sein kann)"],
    ["rescriptum", "Antwortschreiben"],
    ["reservatio mentalis", "geheimer (geistiger) Vorbehalt"],
    ["responsum", "(Antwort) / (Rechts)auskunft / (Rechts)gutachten"],
    ["restitutio", "Wiederherstellung, Wiedereinsetzung"],
    ["reus", "Angeklagter"],
    ["revisio in factum", "Überprüfung in Bezug auf die Sachverhaltsfeststellung"],
    ["revisio in iure", "Überprüfung in Bezug auf die rechtliche Beurteilung"],
    ["revisio", "streitverfangene Sache"],
    ["revocatio mandati", "Widerrruf der Vollmacht"],
    ["revocatio testamenti", "Widerruf des Testaments"],
    ["revocatio", "Widerruf"],
    ["salarium", "Sold, Diät, Honorar"],
    ["satisdatio", "Sicherheitsleistung durch den Bürger"],
    ["scelus", "Verbrechen, Untat"],
    ["scire leges non hoc est verba earum tenere sed vim ac potestatem",
     "die Gesetze zu kennen bedeutet nicht, an ihren Worten zu haften, sondern ihren Sinn und ihre Bedeutung zu begreifen"],
    ["secundum verba", "gemäß der Erklärung"],
    ["secundum voluntatem", "gemäß dem Willen"],
    ["semel heres semper heres", "einmal Erbe, immer Erbe"],
    ["semel maior semper maior", "einmal volljährig, immer volljährig"],
    ["semper in dubiis benigniora praeferenda", "im Zweifel ist immer das Günstigere vorzuziehen"],
    ["senatus consultum", "Senatsbeschluss"],
    ["senatus", "Senat"],
    ["sententia facit ius", "ein Urteil schafft Recht"],
    ["sententia", "Urteil / Spruch"],
    ["separatio bonorum", "Nachlassabsonderung"],
    ["separatio", "Trennung"],
    ["servitium", "Sklavendienst, Sklaverei"],
    ["servitus praedio utilis esse debet", "die Dienstbarkeit muss dem (herrschenden) Grundstück nützlich sein"],
    ["servitus servitutis esse non potest",
     "die Dienstbarkeit kann nicht Gegenstand einer weiteren Dienstbarkeit sein"],
    ["servitus", "Dienstbarkeit"],
    ["servus", "der Sklave, Unfreie, Diener"],
    ["sic utere tuo ut alienum non laedas", "benutze das Deine so, dass du das Fremde nicht verletzt"],
    ["sine", "ohne"],
    ["sine obligo", "ohne Verpflichtung"],
    ["sine tempore (s.t.)", "pünktlich, ohne Frist ('ohne Zeit')"],
    ["singularia non sunt extendenda", "Sonderregeln dürfer nicht ausgedehnt werden"],
    ["societas delinquere non potest", "eine Gesellschaft kann kein Delikt begehen"],
    ["societas",
     "Gesellschaft / Gesellschaftsvertrag (Zusammenschluss zweier oder mehrere Personen zur Verfolgung eines gemeinsamen wirtschaftlichen Zwecks)"],
    ["socius", "Gesellschafter"],
    ["solutio", "Schulderfüllung"],
    ["species", "Einzelsache, das individuelle Stück"],
    ["specificatio", "Verarbeitung"],
    ["sponas", "Braut"],
    ["sponsio", "Bürgschaft / Gelobung / Angelobung (förmliches) Versprechen"],
    ["sponsor", "Bürge"],
    ["sponsus", "Bräutigam"],
    ["status familiae", "Zugehörigkeit zum agnatischen Familienverband"],
    ["status libertatis", "Zugehörigkeit zur Gemeinschaft (dem Stand) der freien Menschen"],
    ["status personae", "personenrechtliche Stellung des Einzelnen"],
    ["status quo", "gegenwärtiger Zustand"],
    ["status", "Stand, Zustand (insbes. Personenstand)"],
    ["statutum", "Satzung, Gesetz (Status)"],
    ["stipulatio", "formgebundenes mündliches (Schuld)Versprechen"],
    ["stricto sensu", "im strengen Sinn, genau genommen"],
    ["sub", "unter"],
    ["substitutio", "Ersetzung"],
    ["substitutus", "Ersatzmann, Ersatzerbe"],
    ["succedere in iura defuncti", "in die Rechte des Verstorbenen nachfolgen"],
    ["succedere in locum defuncti", "an die Stelle des Erblassers treten, nachrücken"],
    ["successio ab intestatio", "Erbfolge ohne Testament"],
    ["successio ex testamento", "testamentarische Erbfolge"],
    ["successio in universitatem", "Gesamtrechtsnachfolge"],
    ["successio", "Rechtsnachfolge, Erbfolge"],
    ["sui generes", "eigener Art (außerhalb des Schemas)"],
    ["sui iuris", "'seines eigenen Rechts', eigenberechtigt"],
    ["summa divisio", "erste Einteilung / oberste Einteilung"],
    ["superficies solo cedit", "die Oberfläche weicht dem Boden"],
    ["superficies", "Bauwerk, Oberfläche"],
    ["superfluum n. / hyperocha", "Überfluss / Übererlös"],
    ["suum cuique", "jedem das Seine"],
    ["tubula", "Schriftstück, Urkunde"],
    ["tempus", "Zeit, Zeitraum"],
    ["tenor", "Hauptaussage, wesentlicher Inhalt"],
    ["terra nullius", "Niemandsland"],
    ["testamenti factio activa", "Testierfähigkeit"],
    ["testamenti factio passiva", "Fähigkeit, als Erbe eingesetzt zu werden"],
    ["testamentum facere", "ein Testament machen / testieren"],
    ["testamentum reciprocum", "wechselseitiges Testament"],
    ["testamentum ruptum", "das zerstörte (ungültige) Testament"],
    ["testamentum simultaneum", "gemeinschaftliches Testament"],
    ["testamentum", "Testament"],
    ["testimonium", "Zeugnis"],
    ["testis", "Zeuge"],
    ["titulus", "Titel, Grund, Rechtsgrund"],
    ["traditio bervi manu",
     "Besitzübergabe kurzer Hand (Form des Besitzerwerbs ohne körperliche Übergabe durch bloße Erklärung)"],
    ["traditio longa manu", "Übergabe durch die lange Hand (körperliche Übergabe)"],
    ["traditio per chartam", "Übergabe durch eine Urkunde, an welcher das Recht an der Sache verbrieft ist"],
    ["traditio", "Übergabe in den Besitz, Besitzübertragung, Überlieferung"],
    ["transactio", "Vergleich, Abmachung"],
    ["tres faciunt collegium", "drei bilden einen Verein"],
    ["trinoctium", "Zeitraum von drei Nächten"],
    ["turpitudo", "Schändlichkeit"],
    ["tutela impuberum", "Vormundschaft über die Unmündigen"],
    ["tutela", "Vormundschaft"],
    ["tutor dativus", "der bestellte Vormund"],
    ["tutor legitimus", "der gesetzmäßige/ gesetzliche Vormund"],
    ["tutor testamentarius", "testamentarischer Vormund"],
    ["tutor", "Vormund"],
    ["ubi eadem ratio, ibi eadem legis dispositio", "wo derselbe Grund, dort auch dasselbe gesetzliche Gebot"],
    ["ubi iudex, ibi iudicium", "wo ein Richter, da eine Entscheidung"],
    ["ubi rem meam invenio, ibi vindico", "wo ich meine Sache vorfinde, da beanspruche ich sie"],
    ["ultima ratio", "letzte, äußerste Maßnahme"],
    ["ultima voluntas", "letzter Wille"],
    ["ultra alterum tantum", "mehr als das Doppelte"],
    ["ultra posse nemo tenetur", "über das Mögliche hinaus wird niemand verpflichtet"],
    ["ultra vires", "über das Können hinaus"],
    ["unitas", "Einheit, Vereinigung"],
    ["universitas", "(Personen-)Gesamtheit, Körperschaft"],
    ["uno actu", "in einem Akt"],
    ["urbs", "Stadt"],
    ["usucapio est adiectio dominii per continuationem possessionis",
     "Ersitzung ist Eigentumserwerb infolge fortdauernden Besitzes"],
    ["usucapio libertatis", "Ersitzung der Freiheit"],
    ["usucapio pro herede", "Ersitzung anstelle des Erben"],
    ["usucapio servitutis", "Ersitzung einer Servitut"],
    ["usucapio", "Ersitzung"],
    ["usurae ex pacto", "vertraglich vereinbarte Zinsen"],
    ["usurae legales", "gesetzliche Zinsen"],
    ["usurae", "Zinsen"],
    ["usureceptio", "Rückersitzung des Eigentums"],
    ["usurpatio", "widerrechtliche Besitzergreifung"],
    ["usus", "Gebrauch, Gebrauchsrecht"],
    ["ususfructus", "Nießbrauch, Nutznießung"],
    ["utile per inutile non vitiatur", "Brauchbares wird durch Unbrauchbares nicht verdorben (Teilnichtigkeit)"],
    ["utilitas publica", "öffentliches Interesse"],
    ["utilitas", "Nützlichkeit"],
    ["utiliter gestum", "nützlich geführt"],
    ["uxor in manu", "die unter der Gewalt des Mannes stehende Ehefrau"],
    ["uxor non in manu", "gewaltfreie Ehefrau / nicht unter Gewalt stehende Ehefrau"],
    ["uxor", "die Ehefrau, Gattin"],
    ["vadimonium", "Bürgschaft, Bürgschaftsleistung"],
    ["venditio", "Verkauf"],
    ["venditor", "der Verkäufer"],
    ["venia docendi (legendi)", "die Erlaubnis des Lehrens (des Lesens)"],
    ["venia", "Gnade, Begnadigung"],
    ["venire contra factum proprium", "Auftreten gegen ein eigenes Tun"],
    ["verba contractus sunt lex contractus", "die Worte eines Vertrages sind das Gesetz des Vertrages"],
    ["verba volant, scripta manent", "Worte verfliegen, das Geschriebene bleibt"],
    ["verbi causa", "des Wortes wegen, aufgrund des Wortes, zum Beispiel"],
    ["verbum", "Wort, Aussage"],
    ["veritas praevalet solemnitati", "die Wahrheit geht der Form vor"],
    ["veritas", "Wahrheit, Wirklichkeit, Aufrichtigkeit, Rechtlichkeit"],
    ["versio", "Bereicherung / Variante"],
    ["verum tacere et falsum asserere paria sunt",
     "die Wahrheit verschweigen und etwas Falsches versichern ist das Gleiche"],
    ["vi, clam, precario",
     "durch/mit Gewalt, gewaltsam / heimlich / 'bittweise', aufgrund einer Bittleihe"],
    ["via", "Straße, Fahrrecht"],
    ["vice versa", "umgekehrt"],
    ["vidaet = videatur", "es möge gesehen werden"],
    ["vim vi repellere licet", "es ist erlaubt, Gewalt mit Gewalt zurückzuschlagen"],
    ["vindicta", "Befreiung, Rettung, Strafe, Rache"],
    ["vir bonus", "der gute Mann, Maßmensch"],
    ["vis absoluta", "absolute (unwiderstehliche) Gewalt"],
    ["vis compulsiva", "willensbeugende (zwingende) Gewalt"],
    ["vis major", "höhere Gewalt"],
    ["vis, vim f.", "Kraft, Gewalt"],
    ["vitiosus", "krankhaft, fehlerhaft"],
    ["vitium", "Fehler, Mangel"],
    ["viventis nulla hereditas", "die Erbschaft eines Lebenden gibt es nicht"],
    ["volenti non fit iniuria", "dem Einwilligenden geschieht kein Unrecht"],
    ["voluntas", "Wille, Absicht"],
    ["voluntatem declarare", "seinen Willen erklären, ausdrücken"],
    ["votum", "Stimme"]
]


def find_similar_answers(vocal_index) -> List[int]:
    similar_answers = []

    question, answer = latin_data[vocal_index]

    similar_candidates = []
    latin_data_preprocessed = np.array([[i, latin_data[i][1]] for i in range(len(latin_data)) if
                                        len(answer) * 0.4 < len(latin_data[i][1]) < len(
                                            answer) * 1.6 and i != vocal_index])

    embedding_question = model.encode(answer, convert_to_tensor=True)

    embedding_candidate = model.encode(latin_data_preprocessed[:, 1].tolist(), convert_to_tensor=True)
    # Compute cosine similarity between text pairs
    similarity = util.pytorch_cos_sim(embedding_question, embedding_candidate).tolist()[0]

    for i in range(len(similarity)):
        similar_candidates.append((i, similarity[i]))

    # similar_candidates.append((vocal_index, 1.0))
    similar_candidates.sort(key=lambda x: x[1], reverse=True)

    # Print the similarity scores
    for i in range(0, min(len(similar_candidates), 10)):
        similar_answers.append(int(latin_data_preprocessed[similar_candidates[i][0]][0]))

    return similar_answers


def switch_latin_german():
    global latin_data
    latin_data = [(b, a) for a, b in latin_data]


def calculate_similarity(filename):
    result = []

    if os.path.exists(filename):
        with open(filename, "r") as file:
            result = json.load(file)

        print(f"Loaded {len(result)} similar answers from {filename}")

    try:
        for i in tqdm(range(len(result), len(latin_data), 1), desc=f"Finding similar answers, {filename}",
                      position=0):
            result.append([i, find_similar_answers(i)])
    except KeyboardInterrupt:
        print(f"Interrupted by user, saving data to {filename}")

    with open(filename, "w") as file:
        json.dump(result, file, indent=4, ensure_ascii=False)


def main():
    calculate_similarity("latin_to_german.json")
    switch_latin_german()
    calculate_similarity("german_to_latin.json")


if __name__ == '__main__':
    main()
